[package]
name = "actix-cache"
version = "0.1.0"
authors = ["Belousow Makc <lib.bmw@gmail.com>", "Andrey Ermilov <andrerm@ya.ru>"]
edition = "2018"
description = "Actix cache actor."
license-file = "LICENSE"

[dependencies]
actix = "0.9"
log = "0.4"
actix-rt = "1"
actix-cache-redis = "0.1"
actix-cache-backend = "0.1"
serde_json = "1"
serde_qs = { version = "0.6", optional = true }
actix-cache-derive = { version = "0.1", optional = true }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"

[dev-dependencies]
env_logger = "0.7"
actix_derive = "0.5"

[workspace]
members = [
  ".",
  "actix-cache-redis",
  "actix-cache-backend",
  "actix-cache-derive",
]

[patch.crates-io]
actix-cache = { path = "." }
actix-cache-redis = { path = "actix-cache-redis" }
actix-cache-backend = { path = "actix-cache-backend" }
actix-cache-derive = { path = "actix-cache-derive" }

[[example]]
name = "debug"
required-features = ["derive"]

[[example]]
name = "async_backend"
required-features = ["derive"]

[features]
derive = ["actix-cache-derive", "serde_qs"]
