[package]
name = "actix-cache-derive"
version = "0.1.0"
authors = ["Andrey Ermilov <andrerm@ya.ru>"]
edition = "2018"

[dependencies]
syn = "1"
quote = "1"
serde = "1"
proc-macro2 = "1"

[lib]
proc-macro = true
