[package]
name = "hitbox-examples"
version = "0.0.0"
publish = false
edition = "2018"

[features]
default = []

[dev-dependencies]
hitbox = { path = "../hitbox", features = ["derive"] }
hitbox-actix = { path = "../hitbox-actix", features = ["redis"] }
hitbox-axum = { path = "../hitbox-axum" }
actix = "0.12"
log = "0.4"
actix-rt = "2"
serde_json = "1"
serde_qs = { version = "0.8" }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
prometheus = { version = "0.12" }
env_logger = "0.9"
actix_derive = "0.6"
actix-web = "3"
tracing = "0.1"
tracing-subscriber = "0.2"
axum = "0.2.4"
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4.8", features = ["full"] }