[package]
name = "hitbox-configuration"
version = "0.1.0"
edition = "2024"

[dependencies]
hitbox = { path = "../hitbox/" }
hitbox-core = { path = "../hitbox-core/" }
hitbox-http = { path = "../hitbox-http/" }
http = "1"
hyper = "1.6"
async-trait = "0.1"
serde = { version = "1", features = ["derive", "alloc"] }
serde_json = "1"
serde_yaml = "0.9"
indexmap = { version = "2.10", features = ["serde"] }
thiserror = "2"
marked-yaml = { version = "0.8.0", optional = true }
serde_yml = { version = "0.0.12", optional = true }
yaml-rust2 = { version = "0.10.4", optional = true }
serde_yaml_ng = { version = "0.10.0", optional = true }


[dev-dependencies]
pretty_assertions = "1.4"
tokio = { version = "1", features = [
    "test-util",
    "macros",
], default-features = false }
bytes = "1"
hitbox = { path = "../hitbox", version = "0.1" }
http-body-util = "0.1"

[features]
marked-yaml = ["dep:marked-yaml"]
serde_yml = ["dep:serde_yml"]
yaml-rust2 = ["dep:yaml-rust2"]
serde_yaml_ng = ["dep:serde_yaml_ng"]
